---
- name: Create shared resources directory
  file:
    path: "{{ config_dirs.nifi_external_config }}"
    state: "directory"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Copy nifi.properties template
  template:
    src: "templates/nifi.properties.j2"
    dest: "{{ config_dirs.nifi_home }}/conf/nifi.properties"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Copy bootstrap.conf template
  template:
    src: "templates/bootstrap.conf.j2"
    dest: "{{ config_dirs.nifi_home }}/conf/bootstrap.conf"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Copy state-management.xml template
  template:
    src: "templates/state-management.xml.j2"
    dest: "{{ config_dirs.nifi_home }}/conf/state-management.xml"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Copy authorizers.xml template
  template:
    src: "templates/authorizers.xml.j2"
    dest: "{{ config_dirs.nifi_home }}/conf/authorizers.xml"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Copy logback.xml template
  template:
    src: "templates/logback.xml.j2"
    dest: "{{ config_dirs.nifi_home }}/conf/logback.xml"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Copy login-identity-providers.xml template
  template:
    src: "templates/login-identity-providers.xml.j2"
    dest: "{{ config_dirs.nifi_home }}/conf/login-identity-providers.xml"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"