---
- name: Copy systemd template
  template:
    src: "templates/nifi.service.j2"
    dest: "/etc/systemd/system/nifi.service"

- name: Re/Start NiFi
  service:
    name: "nifi.service"
    state: restarted
    daemon_reload: yes
    enabled: yes
