---
- name: Create Zookeeper data directory
  file:
    path: "{{ zookeeper.dataDir }}"
    state: "directory"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Create Zookeeper ID file
  copy:
    content: "{{ zookeeper_myid }}"
    dest: "{{ zookeeper.dataDir }}/myid"

- name: Update zookeeper.properties
  lineinfile:
    path: "{{ nifi_config_dirs.home }}/conf/zookeeper.properties"
    line: "{{ item.key }}={{ item.value }}"
    regexp: "^{{ item.key }}"
  with_dict: "{{ zookeeper }}"
